[server]
bind_addr = "0.0.0.0:4000"
default_token = "default_token_if_not_specify"
default_cloud_backend = "http://127.0.0.1:4000"
jwt_secret = "your-super-secret-and-long-jwt-secret"


[server.transport]
type = "tcp"

[server.services.echo]
bind_addr = "0.0.0.0:2334"
